#see for java tunning https://docs.oracle.com/cd/E15523_01/web.1111/e13814/jvm_tuning.htm#PERFM161
version: '3.8'
services:

 ##########################################################################     
 #rabbitmq
 ##########################################################################
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    ports:
       - 5672:5672
       - 15672:15672
    volumes:
       - ./dados:/var/lib/rabbitmq/
    environment:
       - RABBITMQ_DEFAULT_USER=guest
       - RABBITMQ_DEFAULT_PASS=guest
 ##########################################################################     
 #micro-clientes
 ##########################################################################
  micro-clientes:
    container_name: db-micro-clientes
    image: 
    depends_on:
      - rabbitmq
    ports:
      - 8089:8089
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
 ##########################################################################     
 #micro-cuentamovimientos
 ########################################################################## 
  micro-cuentamovimientos:
    container_name: db-micro-cuentamovimientos
    image: santbetv/microservice-docker-serviciocuentamovimiento:0.0.1-SNAPSHOT
    depends_on:
      - rabbitmq
      - micro-clientes
    ports:
      - 8090:8090
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
